### ISSUE TITLE
[QQ 8.8.5.5570] 闪退

### ISSUE THREAD

**Issue by lidoworld** [ferredoxin/QNotified#1008]
**QQ(TIM)版本/QQ(TIM) Version**

8.8.5.5570

**模块版本/Module Version**

0.8.20.5236021

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

LSP 1.5.1 5898

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)

闪退。
一天大概能出现2次左右，都是在主界面进入某个群/私聊的时候。
会卡在进入聊天画面即将完成的时候（聊天界面离左边屏幕还差10%的时候卡住 几秒后QQCrash）。
尝试排除法排除哪个功能会导致这个情况，但发现关闭所有功能都能复现。

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）
发现LSP有日志，刚好这次记得去复制了一份，不知道有用没。
LSPosed Log
--------- beginning of information
Manufacturer: Xiaomi
Brand: Redmi
Device: alioth
Product: alioth
Model: M2012K11AC
Fingerprint: Redmi/alioth/alioth:11/RKQ1.200826.002/V12.5.6.0.RKHCNXM:user/release-keys
ROM description: alioth-user 11 RKQ1.200826.002 V12.5.6.0.RKHCNXM release-keys
Architecture: arm64-v8a
Android build: RKQ1.200826.002
Android version: 11
Android sdk: 30
LSPosed version: v1.5.1 (5898)
Riru version: v26.1.1.r500.45d2706e83 (500)
Riru api: 26
Magisk: 23.0 (23000)
2021-08-20 11:43:27.027 I/com.tencent.mobileqq(8472-8472): com.tencent.mobileqq com.tencent.mobileqq.activity.TextPreviewActivity@172ded3
2021-08-20 11:43:53.053 I/com.tencent.mobileqq(8472-8472): com.tencent.mobileqq com.tencent.mobileqq.activity.TroopAssistantActivity@f6d2fad
2021-08-20 11:43:55.055 I/com.tencent.mobileqq(8472-8472): com.tencent.mobileqq com.tencent.mobileqq.activity.ChatActivity@c2b0923
2021-08-20 11:43:59.059 I/com.tencent.mobileqq:peak(21993-21993): com.tencent.mobileqq:peak com.tencent.mobileqq.richmediabrowser.AIOGalleryActivity@df680cc
2021-08-20 11:45:38.038 I/com.tencent.mobileqq(8472-8472): com.tencent.mobileqq com.tencent.mobileqq.activity.SplashActivity@d1aa7e3
2021-08-20 11:45:39.039 I/com.tencent.mobileqq:peak(24602-24602): com.tencent.mobileqq:peak com.tencent.mobileqq.richmediabrowser.AIOGalleryActivity@ba111fc
2021-08-20 11:45:51.051 I/com.tencent.mobileqq(8472-8472): com.tencent.mobileqq com.tencent.mobileqq.activity.SplashActivity@ba61804
2021-08-20 11:45:55.055 I/com.tencent.mobileqq(8472-8472): com.tencent.mobileqq com.tencent.mobileqq.activity.ChatActivity@a5530c3
2021-08-20 11:46:00.000 I/com.tencent.mobileqq(8472-8472): com.tencent.mobileqq com.tencent.mobileqq.activity.ChatActivity@1d589d3
2021-08-20 11:46:19.019 I/com.tencent.mobileqq:peak(24602-24602): com.tencent.mobileqq:peak com.tencent.mobileqq.richmediabrowser.AIOGalleryActivity@4ff5bdd
2021-08-20 11:47:22.022 I/com.tencent.mobileqq(26567-26567): com.tencent.mobileqq loading com.fkzhang.qqxposed
2021-08-20 11:47:22.022 I/com.tencent.mobileqq(26567-26567): QX模块 2.8_1.15(49,1)
2021-08-20 11:47:22.022 I/com.tencent.mobileqq(26567-26567): com.fkzhang.qqxposed (2.8): QQ version 8.8.5(1858)
2021-08-20 11:47:22.022 I/com.tencent.mobileqq(26567-26567): com.fkzhang.qqxposed load time: 545
2021-08-20 11:47:22.022 I/com.tencent.mobileqq(26567-26567): com.tencent.mobileqq com.tencent.mobileqq.activity.SplashActivity@b1d5118

</code></pre></details>

**Comment by singleNeuron** [comment]
@lidoworld 坏耶，我也闪退，QQ855

**Comment by Neubulae** [comment]
我也闪退…

**Comment by cinit** [comment]
QQ8.5.0.5025 同样闪退
以下crash皆为UncaughtException, 使用Scoop抓取
安卓11, LSPosed v1.4.7 (5803)

<details><summary>StackTrace1</summary><pre><code>
java.lang.IncompatibleClassChangeError: Class 'com.tencent.imcore.message.QQMessageFacade' does not implement interface 'java.lang.CharSequence' in call to 'int java.lang.CharSequence.length()' (declaration of 'android.text.TextUtils' appears in /system/framework/framework.jar!classes3.dex)
	at android.text.TextUtils.isEmpty(TextUtils.java:543)
	at com.tencent.imcore.message.QQMessageFacade.e(P:1165)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:107)
	at LspHooker_.e(Unknown Source:11)
	at com.tencent.imcore.message.QQMessageFacade.a(P:1051)
	at com.tencent.imcore.message.QQMessageFacade.a(P:938)
	at com.tencent.mobileqq.troop.data.TroopMessageProcessor.a(P:749)
	at com.tencent.mobileqq.troop.data.TroopMessageProcessor.a(P:133)
	at com.tencent.mobileqq.app.MessageHandler.b(P:2660)
	at com.tencent.mobileqq.app.MessageHandler.c(P:3703)
	at com.tencent.mobileqq.app.MessageHandler.a(P:3663)
	at com.tencent.mobileqq.app.MessageHandler.onReceive(P:3598)
	at com.tencent.mobileqq.service.MobileQQServiceBase.dispatchToHandler(P:265)
	at com.tencent.mobileqq.service.MobileQQServiceBase.handleResponse(P:229)
	at com.tencent.mobileqq.service.MobileQQServiceExtend.handleResponse(P:789)
	at com.tencent.common.app.AppInterface.receiveToService(P:142)
	at com.tencent.mobileqq.app.QQAppInterface.receiveToService(P:6119)
	at com.tencent.mobileqq.compatible.TempServlet.onReceive(P:46)
	at mqq.app.MSFServlet.onReceive(P:36)
	at mqq.app.ServletContainer.notifyMSFServlet(P:130)
	at mqq.app.MainService.receiveMessageFromMSF(P:266)
	at mqq.app.MainService.access$500(P:67)
	at mqq.app.MainService$4.onRecvCmdPush(P:910)
	at com.tencent.mobileqq.msf.sdk.MsfRespHandleUtil.handlePushMsg(P:187)
	at mqq.app.MainService$2.run(P:508)
	at java.lang.Thread.run(Thread.java:923)
</code></pre></details>

<details><summary>StackTrace2</summary><pre><code>
java.lang.NoSuchMethodError: No interface method ()B in class Ljava/lang/Object; or its super classes (declaration of 'java.lang.Object' appears in /apex/com.android.art/javalib/core-oj.jar)
	at com.tencent.imcore.message.QQMessageFacade.e(P:1171)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:107)
	at LspHooker_.e(Unknown Source:11)
	at com.tencent.imcore.message.QQMessageFacade.a(P:1051)
	at com.tencent.imcore.message.QQMessageFacade.a(P:938)
	at com.tencent.mobileqq.troop.data.TroopMessageProcessor.a(P:749)
	at com.tencent.mobileqq.troop.data.TroopMessageProcessor.a(P:133)
	at com.tencent.mobileqq.app.MessageHandler.b(P:2660)
	at com.tencent.mobileqq.app.MessageHandler.c(P:3703)
	at com.tencent.mobileqq.app.MessageHandler.a(P:3663)
	at com.tencent.mobileqq.app.MessageHandler.onReceive(P:3598)
	at com.tencent.mobileqq.service.MobileQQServiceBase.dispatchToHandler(P:265)
	at com.tencent.mobileqq.service.MobileQQServiceBase.handleResponse(P:229)
	at com.tencent.mobileqq.service.MobileQQServiceExtend.handleResponse(P:789)
	at com.tencent.common.app.AppInterface.receiveToService(P:142)
	at com.tencent.mobileqq.app.QQAppInterface.receiveToService(P:6119)
	at com.tencent.mobileqq.compatible.TempServlet.onReceive(P:46)
	at mqq.app.MSFServlet.onReceive(P:36)
	at mqq.app.ServletContainer.notifyMSFServlet(P:130)
	at mqq.app.MainService.receiveMessageFromMSF(P:266)
	at mqq.app.MainService.access$500(P:67)
	at mqq.app.MainService$4.onRecvCmdPush(P:910)
	at com.tencent.mobileqq.msf.sdk.MsfRespHandleUtil.handlePushMsg(P:187)
	at mqq.app.MainService$2.run(P:508)
	at java.lang.Thread.run(Thread.java:923)
</code></pre></details>

<details><summary>StackTrace3</summary><pre><code>
java.lang.IncompatibleClassChangeError: Class 'com.tencent.mobileqq.data.MessageForText' does not implement interface 'java.lang.CharSequence' in call to 'int java.lang.CharSequence.length()' (declaration of 'android.text.TextUtils' appears in /system/framework/framework.jar!classes3.dex)
	at android.text.TextUtils.isEmpty(TextUtils.java:543)
	at com.tencent.imcore.message.QQMessageFacade.e(P:1168)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:107)
	at LspHooker_.e(Unknown Source:11)
	at com.tencent.imcore.message.QQMessageFacade.a(P:1051)
	at com.tencent.imcore.message.QQMessageFacade.a(P:938)
	at com.tencent.mobileqq.troop.data.TroopMessageProcessor.a(P:749)
	at com.tencent.mobileqq.troop.data.TroopMessageProcessor.a(P:133)
	at com.tencent.mobileqq.app.MessageHandler.b(P:2660)
	at com.tencent.mobileqq.app.MessageHandler.c(P:3703)
	at com.tencent.mobileqq.app.MessageHandler.a(P:3663)
	at com.tencent.mobileqq.app.MessageHandler.onReceive(P:3598)
	at com.tencent.mobileqq.service.MobileQQServiceBase.dispatchToHandler(P:265)
	at com.tencent.mobileqq.service.MobileQQServiceBase.handleResponse(P:229)
	at com.tencent.mobileqq.service.MobileQQServiceExtend.handleResponse(P:789)
	at com.tencent.common.app.AppInterface.receiveToService(P:142)
	at com.tencent.mobileqq.app.QQAppInterface.receiveToService(P:6119)
	at com.tencent.mobileqq.compatible.TempServlet.onReceive(P:46)
	at mqq.app.MSFServlet.onReceive(P:36)
	at mqq.app.ServletContainer.notifyMSFServlet(P:130)
	at mqq.app.MainService.receiveMessageFromMSF(P:266)
	at mqq.app.MainService.access$500(P:67)
	at mqq.app.MainService$4.onRecvCmdPush(P:910)
	at com.tencent.mobileqq.msf.sdk.MsfRespHandleUtil.handlePushMsg(P:187)
	at mqq.app.MainService$2.run(P:508)
	at java.lang.Thread.run(Thread.java:923)
</code></pre></details>

**Comment by singleNeuron** [comment]
直接原因：
```
46.888 F/libc    (5400): Fatal signal 11 (SIGSEGV), code 0 (SI_USER) in tid 5400 (encent.mobileqq), pid 5400 (encent.mobileqq)
46.969 I/ActivityManager(1653): Process com.tencent.mobileqq:qzone (pid 23736) has died: fg  BTOP
47.414 F/DEBUG   (26403): pid: 5400, tid: 5400, name: encent.mobileqq  >>> com.tencent.mobileqq <<<
48.912 W/ActivityTaskManager(1653):   Force finishing activity com.tencent.mobileqq/.activity.SplashActivity
49.111 I/ActivityManager(1653): Process com.tencent.mobileqq (pid 5400) early provider death
49.111 I/ActivityManager(1653): Process com.tencent.mobileqq (pid 5400) has died: fg  TOP 
```

疑似原因：
```
05.729 E/ActivityThread(2494): Activity cooperation.troop.TroopManageProxyActivity has leaked IntentReceiver com.tencent.mobileqq.activity.TroopManageActivity$21@6a7f138 that was originally registered here. Are you missing a call to unregisterReceiver()?
05.729 E/ActivityThread(2494): 	at com.tencent.mobileqq.activity.TroopManageActivity.a(P:1011)
05.729 E/ActivityThread(2494): 	at com.tencent.mobileqq.base.TroopManageBaseActivity.onCreate(P:35)
05.729 E/ActivityThread(2494): 	at com.tencent.mobileqq.pluginsdk.BasePluginActivity.IOnCreate(P:198)
05.729 E/ActivityThread(2494): 	at com.tencent.mobileqq.pluginsdk.PluginProxyActivity.onCreate(P:321)
```

**Comment by singleNeuron** [comment]
> QQ8.5.0.5025 同样闪退
> 以下crash皆为UncaughtException, 使用Scoop抓取
> 安卓11, LSPosed v1.4.7 (5803)
> 
> StackTrace1
> ```
> 
> java.lang.IncompatibleClassChangeError: Class 'com.tencent.imcore.message.QQMessageFacade' does not implement interface 'java.lang.CharSequence' in call to 'int java.lang.CharSequence.length()' (declaration of 'android.text.TextUtils' appears in /system/framework/framework.jar!classes3.dex)
> 	at android.text.TextUtils.isEmpty(TextUtils.java:543)
> 	at com.tencent.imcore.message.QQMessageFacade.e(P:1165)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:107)
> 	at LspHooker_.e(Unknown Source:11)
> 	at com.tencent.imcore.message.QQMessageFacade.a(P:1051)
> 	at com.tencent.imcore.message.QQMessageFacade.a(P:938)
> 	at com.tencent.mobileqq.troop.data.TroopMessageProcessor.a(P:749)
> 	at com.tencent.mobileqq.troop.data.TroopMessageProcessor.a(P:133)
> 	at com.tencent.mobileqq.app.MessageHandler.b(P:2660)
> 	at com.tencent.mobileqq.app.MessageHandler.c(P:3703)
> 	at com.tencent.mobileqq.app.MessageHandler.a(P:3663)
> 	at com.tencent.mobileqq.app.MessageHandler.onReceive(P:3598)
> 	at com.tencent.mobileqq.service.MobileQQServiceBase.dispatchToHandler(P:265)
> 	at com.tencent.mobileqq.service.MobileQQServiceBase.handleResponse(P:229)
> 	at com.tencent.mobileqq.service.MobileQQServiceExtend.handleResponse(P:789)
> 	at com.tencent.common.app.AppInterface.receiveToService(P:142)
> 	at com.tencent.mobileqq.app.QQAppInterface.receiveToService(P:6119)
> 	at com.tencent.mobileqq.compatible.TempServlet.onReceive(P:46)
> 	at mqq.app.MSFServlet.onReceive(P:36)
> 	at mqq.app.ServletContainer.notifyMSFServlet(P:130)
> 	at mqq.app.MainService.receiveMessageFromMSF(P:266)
> 	at mqq.app.MainService.access$500(P:67)
> 	at mqq.app.MainService$4.onRecvCmdPush(P:910)
> 	at com.tencent.mobileqq.msf.sdk.MsfRespHandleUtil.handlePushMsg(P:187)
> 	at mqq.app.MainService$2.run(P:508)
> 	at java.lang.Thread.run(Thread.java:923)
> ```
> 
> StackTrace2
> ```
> 
> java.lang.NoSuchMethodError: No interface method ()B in class Ljava/lang/Object; or its super classes (declaration of 'java.lang.Object' appears in /apex/com.android.art/javalib/core-oj.jar)
> 	at com.tencent.imcore.message.QQMessageFacade.e(P:1171)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:107)
> 	at LspHooker_.e(Unknown Source:11)
> 	at com.tencent.imcore.message.QQMessageFacade.a(P:1051)
> 	at com.tencent.imcore.message.QQMessageFacade.a(P:938)
> 	at com.tencent.mobileqq.troop.data.TroopMessageProcessor.a(P:749)
> 	at com.tencent.mobileqq.troop.data.TroopMessageProcessor.a(P:133)
> 	at com.tencent.mobileqq.app.MessageHandler.b(P:2660)
> 	at com.tencent.mobileqq.app.MessageHandler.c(P:3703)
> 	at com.tencent.mobileqq.app.MessageHandler.a(P:3663)
> 	at com.tencent.mobileqq.app.MessageHandler.onReceive(P:3598)
> 	at com.tencent.mobileqq.service.MobileQQServiceBase.dispatchToHandler(P:265)
> 	at com.tencent.mobileqq.service.MobileQQServiceBase.handleResponse(P:229)
> 	at com.tencent.mobileqq.service.MobileQQServiceExtend.handleResponse(P:789)
> 	at com.tencent.common.app.AppInterface.receiveToService(P:142)
> 	at com.tencent.mobileqq.app.QQAppInterface.receiveToService(P:6119)
> 	at com.tencent.mobileqq.compatible.TempServlet.onReceive(P:46)
> 	at mqq.app.MSFServlet.onReceive(P:36)
> 	at mqq.app.ServletContainer.notifyMSFServlet(P:130)
> 	at mqq.app.MainService.receiveMessageFromMSF(P:266)
> 	at mqq.app.MainService.access$500(P:67)
> 	at mqq.app.MainService$4.onRecvCmdPush(P:910)
> 	at com.tencent.mobileqq.msf.sdk.MsfRespHandleUtil.handlePushMsg(P:187)
> 	at mqq.app.MainService$2.run(P:508)
> 	at java.lang.Thread.run(Thread.java:923)
> ```
> 
> StackTrace3
> ```
> 
> java.lang.IncompatibleClassChangeError: Class 'com.tencent.mobileqq.data.MessageForText' does not implement interface 'java.lang.CharSequence' in call to 'int java.lang.CharSequence.length()' (declaration of 'android.text.TextUtils' appears in /system/framework/framework.jar!classes3.dex)
> 	at android.text.TextUtils.isEmpty(TextUtils.java:543)
> 	at com.tencent.imcore.message.QQMessageFacade.e(P:1168)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:107)
> 	at LspHooker_.e(Unknown Source:11)
> 	at com.tencent.imcore.message.QQMessageFacade.a(P:1051)
> 	at com.tencent.imcore.message.QQMessageFacade.a(P:938)
> 	at com.tencent.mobileqq.troop.data.TroopMessageProcessor.a(P:749)
> 	at com.tencent.mobileqq.troop.data.TroopMessageProcessor.a(P:133)
> 	at com.tencent.mobileqq.app.MessageHandler.b(P:2660)
> 	at com.tencent.mobileqq.app.MessageHandler.c(P:3703)
> 	at com.tencent.mobileqq.app.MessageHandler.a(P:3663)
> 	at com.tencent.mobileqq.app.MessageHandler.onReceive(P:3598)
> 	at com.tencent.mobileqq.service.MobileQQServiceBase.dispatchToHandler(P:265)
> 	at com.tencent.mobileqq.service.MobileQQServiceBase.handleResponse(P:229)
> 	at com.tencent.mobileqq.service.MobileQQServiceExtend.handleResponse(P:789)
> 	at com.tencent.common.app.AppInterface.receiveToService(P:142)
> 	at com.tencent.mobileqq.app.QQAppInterface.receiveToService(P:6119)
> 	at com.tencent.mobileqq.compatible.TempServlet.onReceive(P:46)
> 	at mqq.app.MSFServlet.onReceive(P:36)
> 	at mqq.app.ServletContainer.notifyMSFServlet(P:130)
> 	at mqq.app.MainService.receiveMessageFromMSF(P:266)
> 	at mqq.app.MainService.access$500(P:67)
> 	at mqq.app.MainService$4.onRecvCmdPush(P:910)
> 	at com.tencent.mobileqq.msf.sdk.MsfRespHandleUtil.handlePushMsg(P:187)
> 	at mqq.app.MainService$2.run(P:508)
> 	at java.lang.Thread.run(Thread.java:923)
> ```

为什么你这个堆栈里有lsp但是包名里没有qn

**Comment by singleNeuron** [comment]
![Screenshot_20210821-203651328](https://user-images.githubusercontent.com/23723294/130322053-d1292973-6783-4c56-8e5d-a3b383be75ed.jpg)
确认了是QQ本身的Native出现问题

**Comment by Neubulae** [comment]
??竟然是QQ本身的问题吗！

**Comment by lidoworld** [comment]
QQ到了8.8.20.5865似乎也有这情况
目前排查发现即使一个功能都不都会有这种情况
