### ISSUE TITLE
tim3.4.4显示异常

### ISSUE THREAD

**Issue by Timekang** [ferredoxin/QNotified#1189]
**QQ(TIM)版本/QQ(TIM) Version**
3.4.4.3058
* 

**模块版本/Module Version**
0.8.24.940b465
* 

**使用的框架名称与框架版本/Xposed Framework and Framework Version**
Lsposed 1.6.5(6276)
* 

**问题的具体描述/Detailed Description of the Bug**
最新版tim/qq＋最新版qn使用小窗后会把QQ显示到状态栏
![IMG_20211215_125803](https://user-images.githubusercontent.com/63047935/146126630-d8edece6-7358-480a-9868-14ee6addfdba.jpg)

*  具体描述(如复现BUG所需要的前提和必要操作等)
用最新版qn分屏或开小窗100%复现

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

----part 2 start----
[ 2021-12-15T12:52:20.277    10187: 21459: 21459 I/LSPosed-Bridge  ] Loading module nil.nadph.qnotified from /data/app/~~j1I0pvLzRp5pw6s3FpZjBA==/nil.nadph.qnotified-SmNSWo4chgr8jcXBDwY2iw==/base.apk
[ 2021-12-15T12:52:20.415    10187: 21459: 21459 I/LSPosed-Bridge  ]   Loading class nil.nadph.qnotified.startup.HookEntry
[ 2021-12-15T12:52:21.143    10187: 21584: 21584 I/LSPosed-Bridge  ] Loading module nil.nadph.qnotified from /data/app/~~j1I0pvLzRp5pw6s3FpZjBA==/nil.nadph.qnotified-SmNSWo4chgr8jcXBDwY2iw==/base.apk
[ 2021-12-15T12:52:21.229    10187: 21584: 21584 I/LSPosed-Bridge  ]   Loading class nil.nadph.qnotified.startup.HookEntry
[ 2021-12-15T12:52:21.662    10187: 21459: 21514 E/LSPosed-Bridge  ] java.lang.RuntimeException: VasProfileAntiCrash :Unsupported Version: 3.4.4
	at me.singleneuron.qn_kernel.tlb.ConfigTable.getConfig(ConfigTable.kt:57)
	at cc.ioctl.hook.VasProfileAntiCrash.initOnce(VasProfileAntiCrash.java:61)
	at de.robv.android.xposed.LspHooker.

</code></pre></details>

**Comment by Timekang** [comment]
`[ 2021-12-15T12:52:21.662    10187: 21459: 21514 E/LSPosed-Bridge  ] java.lang.RuntimeException: VasProfileAntiCrash :Unsupported Version: 3.4.4
	at me.singleneuron.qn_kernel.tlb.ConfigTable.getConfig(ConfigTable.kt:57)
	at cc.ioctl.hook.VasProfileAntiCrash.initOnce(VasProfileAntiCrash.java:61)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.doStep(Unknown Source:8)
	at com.tencent.mobileqq.startup.step.Step.step(SourceFile:121)
	at com.tencent.mobileqq.startup.step.Step.doStep(SourceFile:153)
	at com.tencent.mobileqq.startup.step.Step.step(SourceFile:121)
	at anmo.a(SourceFile:885)
	at anmo.handleMessage(SourceFile:898)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:257)
	at android.os.HandlerThread.run(HandlerThread.java:67)`

**Comment by Timekang** [comment]
`[ 2021-12-15T12:52:21.745    10187: 21459: 21514 E/LSPosed-Bridge  ] java.lang.NoSuchMethodException: jqp.unZipFile [class java.io.File, class java.lang.String]
	at java.lang.Class.getMethod(Class.java:2072)
	at java.lang.Class.getMethod(Class.java:1693)
	at cc.ioctl.hook.InterceptZipBomb.initOnce(InterceptZipBomb.java:61)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.doStep(Unknown Source:8)
	at com.tencent.mobileqq.startup.step.Step.step(SourceFile:121)
	at com.tencent.mobileqq.startup.step.Step.doStep(SourceFile:153)
	at com.tencent.mobileqq.startup.step.Step.step(SourceFile:121)
	at anmo.a(SourceFile:885)
	at anmo.handleMessage(SourceFile:898)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:257)
	at android.os.HandlerThread.run(HandlerThread.java:67)`

**Comment by qwq233** [comment]
你确定这是qn问题？关掉还有无现象？

**Comment by Timekang** [comment]
目前用的qn0.8.19版本和qq8.7.0，一切正常。新版qq用旧版qn功能上不太兼容，新版qq配合新版qn会出现上面的问题

**Comment by qwq233** [comment]
> 目前用的qn0.8.19版本和qq8.7.0，一切正常。新版qq用旧版qn功能上不太兼容，新版qq配合新版qn会出现上面的问题

我问关掉还有没有这个问题 用的miui?

**Comment by Timekang** [comment]
不用qn，单新版qq是正常的。系统originos
