### ISSUE TITLE
[8.8.55] 开启QN进入QQ报错

### ISSUE THREAD

**Issue by getcurl** [ferredoxin/QNotified#1233]
**QQ(TIM)版本/QQ(TIM) Version**
8.8.55
* 

**模块版本/Module Version**
1.0.0.e1ec5bc
* 

**使用的框架名称与框架版本/Xposed Framework and Framework Version**
太极·阴
* 

**问题的具体描述/Detailed Description of the Bug**
开启QN打开QQ报错 关了QN就不报错(日志优绿逗生成)
*  具体描述(如复现BUG所需要的前提和必要操作等)

**-----QQ子线程未捕获异常信息输出开始----------
Time:2022-01-21 23:26:04
手机厂商:HUAWEI
品牌:HUAWEI
型号:SEA-AL10
系统版本:Android 10
QQ版本号:8.8.55.6900
线程:AppCenter.Looper
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
at com.microsoft.appcenter.ingestion.models.StartServiceLog.read(StartServiceLog.java:76)(可能为 nil.nadph.qnotified 中的方法)
at com.microsoft.appcenter.ingestion.models.json.DefaultLogSerializer.readLog(DefaultLogSerializer.java:51)(可能为 nil.nadph.qnotified 中的方法)
at com.microsoft.appcenter.ingestion.models.json.DefaultLogSerializer.deserializeLog(DefaultLogSerializer.java:64)(可能为 nil.nadph.qnotified 中的方法)
at com.microsoft.appcenter.persistence.DatabasePersistence.getLogs(DatabasePersistence.java:499)(可能为 nil.nadph.qnotified 中的方法)
at com.microsoft.appcenter.channel.DefaultChannel.triggerIngestion(DefaultChannel.java:480)(可能为 nil.nadph.qnotified 中的方法)
at com.microsoft.appcenter.channel.DefaultChannel.checkPendingLogs(DefaultChannel.java:726)(可能为 nil.nadph.qnotified 中的方法)
at com.microsoft.appcenter.channel.DefaultChannel.addGroup(DefaultChannel.java:240)(可能为 nil.nadph.qnotified 中的方法)
at com.microsoft.appcenter.AppCenter.finishConfiguration(AppCenter.java:865)(可能为 nil.nadph.qnotified 中的方法)
at com.microsoft.appcenter.AppCenter.access$500(AppCenter.java:61)(可能为 nil.nadph.qnotified 中的方法)
at com.microsoft.appcenter.AppCenter$5.run(AppCenter.java:737)(可能为 nil.nadph.qnotified 中的方法)
at android.os.Handler.handleCallback(Handler.java:900)
at android.os.Handler.dispatchMessage(Handler.java:103)
at android.os.Looper.loop(Looper.java:219)
at android.os.HandlerThread.run(HandlerThread.java:67)
-----QQ子线程未捕获异常信息输出结束----------

/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by NextAlone** [comment]
@getcurl 是否影响qn使用？

**Comment by getcurl** [comment]
@NextAlone QN不受影响 但是QQ无法连接网络，发送消息、接收消息不可以，其他都还可以 就很离谱

**Comment by Cryolitia** [comment]
Problem located, due to https://github.com/microsoft/appcenter-sdk-android/issues/1584

**Comment by getcurl** [comment]
> 问题已定位，由于[microsoft/appcenter-sdk-android#1584](https://github.com/microsoft/appcenter-sdk-android/issues/1584)

I don't know how long it'll take to fix it

**Comment by Cryolitia** [comment]
https://github.com/ferredoxin/QNotified/commit/9cf0e0d7a7137802afe1908aa60215ad7118e790
