### ISSUE TITLE
[QQ8.8.0] 自定义聊天小尾巴崩溃

### ISSUE THREAD

**Issue by pinksheer** [ferredoxin/QNotified#1238]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ8.8.0

**模块版本/Module Version**

* 1.0.0

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* LSPosed 1.6.5

**问题的具体描述/Detailed Description of the Bug**

*  在Bate测试功能中点击自定义聊天小尾巴，QQ会崩溃

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

[ 2022-01-22T23:47:12.344    10133: 29852: 29852 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.RuntimeException: Unable to resume activity {com.tencent.mobileqq/cc.ioctl.activity.ChatTailActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4205)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
	at cc.ioctl.activity.ChatTailActivity.doOnResume(ChatTailActivity.java:231)
	at mqq.app.AppActivity.onResume(P:374)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1453)
	at android.app.Activity.performResume(Activity.java:7958)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195)
	... 11 more

</code></pre></details>

**Comment by Cryolitia** [comment]
@pinksheer 空指针了

**Comment by Cryolitia** [comment]
@Cryolitia https://t.me/QNotified_CI/346

试一下这个

**Comment by pinksheer** [comment]
> @Cryolitia https://t.me/QNotified_CI/346
> 
> 试一下这个

一样的，还是崩溃

**Comment by Cryolitia** [comment]
@pinksheer 有其他开发者可以复现问题吗
