### ISSUE TITLE
[QQ 8.8.68] 主页 Banner 活动图片造成QQ闪退

### ISSUE THREAD

**Issue by fankes** [ferredoxin/QNotified#1244]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ 8.8.68

**模块版本/Module Version**

* 1.0.0.51c9094

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* Lsposed 1.6.5(1289)

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)

疑似今天QQ更新了一个新年的banner，反复进入QQ后闪退，取消激活模块后恢复正常并展示出了QQ主页顶部那个banner logo，就是点击右侧图标可以关闭的banner，忘记截图了，错误应该是获取不到某个方法或者空指针异常。
新年活动下拉QQ小程序可以抢红包那个活动，模块设置开启了屏蔽净化下拉小程序功能。

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

[ 2022-01-25T10:35:29.677    10257: 24414: 27199 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.RuntimeException: queueIdle encounter business crash. java.lang.NullPointerException: Attempt to invoke virtual method 'void cooperation.vip.qqbanner.widget.NakedEyesView.a()' on a null object reference
	at cooperation.vip.qqbanner.manager.VasADImmersionBannerManager.d(P:270)
	at com.tencent.mobileqq.activity.recent.bannerprocessor.VasADBannerProcessor.h(P:270)
	at com.tencent.mobileqq.activity.recent.bannerprocessor.VasADBannerProcessor.k(P:260)
	at com.tencent.mobileqq.activity.recent.bannerprocessor.VasADBannerProcessor.handleMessage(P:143)
	at com.tencent.mobileqq.utils.CustomHandler.handleMessage(P:25)
	at mqq.os.MqqHandler.dispatchMessage(P:99)
	at mqq.os.MqqMessageQueue.dequeue(P:294)
	at mqq.os.MqqMessageQueue.queueIdle(P:251)
	at android.os.MessageQueue.next(MessageQueue.java:409)
	at android.os.Looper.loopOnce(Looper.java:168)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8205)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

	at mqq.os.MqqMessageQueue$2.run(P:237)
[ 2022-01-25T10:35:29.677    10257: 24414: 27199 E/AndroidRuntime  ] FATAL EXCEPTION: Thread-88
Process: com.tencent.mobileqq, PID: 24414
java.lang.RuntimeException: queueIdle encounter business crash. java.lang.NullPointerException: Attempt to invoke virtual method 'void cooperation.vip.qqbanner.widget.NakedEyesView.a()' on a null object reference
	at cooperation.vip.qqbanner.manager.VasADImmersionBannerManager.d(P:270)
	at com.tencent.mobileqq.activity.recent.bannerprocessor.VasADBannerProcessor.h(P:270)
	at com.tencent.mobileqq.activity.recent.bannerprocessor.VasADBannerProcessor.k(P:260)
	at com.tencent.mobileqq.activity.recent.bannerprocessor.VasADBannerProcessor.handleMessage(P:143)
	at com.tencent.mobileqq.utils.CustomHandler.handleMessage(P:25)
	at mqq.os.MqqHandler.dispatchMessage(P:99)
	at mqq.os.MqqMessageQueue.dequeue(P:294)
	at mqq.os.MqqMessageQueue.queueIdle(P:251)
	at android.os.MessageQueue.next(MessageQueue.java:409)
	at android.os.Looper.loopOnce(Looper.java:168)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8205)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

	at mqq.os.MqqMessageQueue$2.run(P:237)

</code></pre></details>

**Comment by keta1** [comment]
@fankes 等春节过去他就自己好了

**Comment by fankes** [comment]
> @fankes 等春节过去他就自己好了

啊，你也摆烂吗，来过年一起摆（

**Comment by NextAlone** [comment]
@fankes 我刚才遇到了，但我不想修

**Comment by Cryolitia** [comment]
@NextAlone 我倒是没闪退，但是一打开QQ就被吓到了。还跑过来想让你们赶紧写个屏蔽

**Comment by Clansty** [comment]
@fankes 大佬出现了
