### ISSUE TITLE
[QQ8.8.68] 启动qq后一段时间闪退

### ISSUE THREAD

**Issue by RimuruChan** [ferredoxin/QNotified#1253]
**QQ(TIM)版本/QQ(TIM) Version**

* 8.8.68

**模块版本/Module Version**

* 0.8.24

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* lsposed-riru

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)

启动qq
静置
过一段时间后崩溃

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

[ 2022-01-24T17:58:18.530    10232: 32181: 32181 E/LSPosed-Bridge  ] android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffffffff
	at android.content.res.ResourcesImpl.getResourceEntryName(Unknown Source:32)
	at android.content.res.Resources.getResourceEntryName(Unknown Source:2)
	at ᐧʻ.ᴵי$ˆﹳ$ᵢˊ.afterHookedMethod(Unknown Source:38)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.setOnClickListener(Unknown Source:11)
	at com.tencent.mobileqq.emoticonview.EmotionPanelViewPagerAdapter.getSystemSmallEmoticonRelativeLayout(P:404)
	at com.tencent.mobileqq.emoticonview.EmotionPanelViewPagerAdapter.instantiateItem(P:341)
	at androidx.viewpager.widget.PagerAdapter.instantiateItem(P:115)
	at androidx.viewpager.widget.ViewPager.addNewItem(P:1010)
	at androidx.viewpager.widget.ViewPager.populate(P:1192)
	at androidx.viewpager.widget.ViewPager.populate(P:1092)
	at androidx.viewpager.widget.ViewPager.onMeasure(P:1622)
	at android.view.View.measure(Unknown Source:236)
	at android.widget.RelativeLayout.measureChildHorizontal(Unknown Source:90)
	at android.widget.RelativeLayout.onMeasure(Unknown Source:177)
	at android.view.View.measure(Unknown Source:236)
	at android.widget.RelativeLayout.measureChildHorizontal(Unknown Source:90)
	at android.widget.RelativeLayout.onMeasure(Unknown Source:177)
	at com.tencent.mobileqq.emoticonview.EmoticonMainPanel.onMeasure(P:346)
	at android.view.View.measure(Unknown Source:236)
	at com.tencent.widget.XPanelContainer.c(P:1032)
	at com.tencent.widget.XPanelContainer.a(P:763)
	at com.tencent.widget.XPanelContainer.onLayout(P:680)
	at android.view.View.layout(Unknown Source:89)
	at android.view.ViewGroup.layout(Unknown Source:21)
	at android.widget.RelativeLayout.onLayout(Unknown Source:42)
	at android.view.View.layout(Unknown Source:89)
	at android.view.ViewGroup.layout(Unknown Source:21)
	at android.widget.RelativeLayout.onLayout(Unknown Source:42)
	at com.tencent.mobileqq.activity.fling.TopGestureLayout.onLayout(P:366)
	at android.view.View.layout(Unknown Source:89)
	at android.view.ViewGroup.layout(Unknown Source:21)
	at com.tencent.mobileqq.widget.DrawerFrame.onLayout(P:312)
	at android.view.View.layout(Unknown Source:89)
	at android.view.ViewGroup.layout(Unknown Source:21)
	at android.widget.FrameLayout.layoutChildren(Unknown Source:160)
	at android.widget.FrameLayout.onLayout(Unknown Source:6)
	at android.view.View.layout(Unknown Source:89)
	at android.view.ViewGroup.layout(Unknown Source:21)
	at android.widget.LinearLayout.setChildFrame(Unknown Source:4)
	at android.widget.LinearLayout.layoutVertical(Unknown Source:184)
	at android.widget.LinearLayout.onLayout(Unknown Source:5)
	at android.view.View.layout(Unknown Source:89)
	at android.view.ViewGroup.layout(Unknown Source:21)
	at android.widget.FrameLayout.layoutChildren(Unknown Source:160)
	at android.widget.FrameLayout.onLayout(Unknown Source:6)
	at com.android.internal.policy.DecorView.onLayout(Unknown Source:0)
	at android.view.View.layout(Unknown Source:89)
	at android.view.ViewGroup.layout(Unknown Source:21)
	at android.view.ViewRootImpl.performLayout(Unknown Source:32)
	at android.view.ViewRootImpl.performTraversals(Unknown Source:2230)
	at android.view.ViewRootImpl.doTraversal(Unknown Source:36)
	at android.view.ViewRootImpl$TraversalRunnable.run(Unknown Source:2)
	at android.view.Choreographer$CallbackRecord.run(Unknown Source:20)
	at android.view.Choreographer.doCallbacks(Unknown Source:84)
	at android.view.Choreographer.doFrame(Unknown Source:328)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Unknown Source:11)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loopOnce(Unknown Source:176)
	at android.os.Looper.loop(Unknown Source:77)
	at android.app.ActivityThread.main(Unknown Source:138)
	at java.lang.reflect.Method.invoke(Native Method)
[ 2022-01-24T18:20:48.379    10232: 32181: 32181 E/LSPosed-Bridge  ] android.content.res.Resources$NotFoundException: Unable to find resource ID #0xffffffff
	at android.content.res.ResourcesImpl.getResourceEntryName(Unknown Source:32)
	at android.content.res.Resources.getResourceEntryName(Unknown Source:2)
	at ᐧʻ.ᴵי$ˆﹳ$ᵢˊ.afterHookedMethod(Unknown Source:38)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.setOnClickListener(Unknown Source:11)
	at com.tencent.mobileqq.emoticonview.EmotionPanelViewPagerAdapter.getSystemSmallEmoticonRelativeLayout(P:404)
	at com.tencent.mobileqq.emoticonview.EmotionPanelViewPagerAdapter.instantiateItem(P:341)
	at androidx.viewpager.widget.PagerAdapter.instantiateItem(P:115)
	at androidx.viewpager.widget.ViewPager.addNewItem(P:1010)
	at androidx.viewpager.widget.ViewPager.populate(P:1224)
	at androidx.viewpager.widget.ViewPager.populate(P:1092)
	at androidx.viewpager.widget.ViewPager.setAdapter(P:540)
	at com.tencent.mobileqq.emoticonview.BasePanelView$6.run(P:1079)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loopOnce(Unknown Source:176)
	at android.os.Looper.loop(Unknown Source:77)
	at android.app.ActivityThread.main(Unknown Source:138)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:306)

</code></pre></details>

**Comment by cinit** [comment]
从提供的 log 来看 (`at ᐧʻ.ᴵי$ˆﹳ$ᵢˊ.afterHookedMethod(Unknown Source:38)`) 这似乎不是 qn 的问题, 请考虑其他模块

**Comment by RimuruChan** [comment]
已更新

**Comment by metaforget** [comment]
我也是一样闪退，楼主怎么解决的?

**Comment by RimuruChan** [comment]
无法进入qn设置和这个是两个问题吧。。

**Comment by qwq233** [comment]
> 无法进入qn设置和这个是两个问题吧。。

啧 那你这个问题解决了吗 还有装了ci版后有没有杀应用

**Comment by RimuruChan** [comment]
> > 无法进入qn设置和这个是两个问题吧。。
> 
> 啧 那你这个问题解决了吗 还有装了ci版后有没有杀应用

试了一下ci版可以进设置了，然后这个闪退问题明天再观察一下，因为他好像要在一定时间段触发。。。

**Comment by RimuruChan** [comment]
崩了但是报错变了，已更新

**Comment by recycle007** [comment]
> 崩了但是报错变了，已更新

更新了1.01还是会出现鸭

**Comment by beixibaobao** [comment]
oh no！更新了1.01也会出现，孩子现在已经无奈关掉qn过年了，呜呜呜

**Comment by youling257** [comment]
[logqq.txt](https://github.com/ferredoxin/QNotified/files/7964031/logqq.txt)
logcat里面的闪退原因是啥

**Comment by bury-2YK** [comment]
我也是

**Comment by bury-2YK** [comment]
![Uploading Screenshot_2022-01-31-22-02-54-870_nil.nadph.qnotified.jpg…]()
