### ISSUE TITLE
[QQ 轻聊版 4.0.0] 模块更新后无法使用 启动QQ即闪退

### ISSUE THREAD

**Issue by Lehmaning** [ferredoxin/QNotified#1254]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ 轻聊版 4.0.0

**模块版本/Module Version**

* Stable Version 1.0.0.d4f980f

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* LSPosed v1.5.3

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)
以往的版本可以使用。。但是更新之后就打不开qq了，打开就会闪退。

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>
FATAL EXCEPTION: AppCenter.Looper
Process: com.tencent.qqlite, PID: 15366
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
	at com.microsoft.appcenter.ingestion.models.StartServiceLog.read(StartServiceLog.java:76)
	at com.microsoft.appcenter.ingestion.models.json.DefaultLogSerializer.readLog(DefaultLogSerializer.java:51)
	at com.microsoft.appcenter.ingestion.models.json.DefaultLogSerializer.deserializeLog(DefaultLogSerializer.java:64)
	at com.microsoft.appcenter.persistence.DatabasePersistence.getLogs(DatabasePersistence.java:499)
	at com.microsoft.appcenter.channel.DefaultChannel.triggerIngestion(DefaultChannel.java:480)
	at com.microsoft.appcenter.channel.DefaultChannel.checkPendingLogs(DefaultChannel.java:726)
	at com.microsoft.appcenter.channel.DefaultChannel.addGroup(DefaultChannel.java:240)
	at com.microsoft.appcenter.AppCenter.finishConfiguration(AppCenter.java:865)
	at com.microsoft.appcenter.AppCenter.access$500(AppCenter.java:61)
	at com.microsoft.appcenter.AppCenter$5.run(AppCenter.java:737)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loop(Unknown Source:250)
	at android.os.HandlerThread.run(Unknown Source:28)
FATAL EXCEPTION: AppCenter.Looper
Process: com.tencent.qqlite, PID: 15835
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
	at com.microsoft.appcenter.ingestion.models.StartServiceLog.read(StartServiceLog.java:76)
	at com.microsoft.appcenter.ingestion.models.json.DefaultLogSerializer.readLog(DefaultLogSerializer.java:51)
	at com.microsoft.appcenter.ingestion.models.json.DefaultLogSerializer.deserializeLog(DefaultLogSerializer.java:64)
	at com.microsoft.appcenter.persistence.DatabasePersistence.getLogs(DatabasePersistence.java:499)
	at com.microsoft.appcenter.channel.DefaultChannel.triggerIngestion(DefaultChannel.java:480)
	at com.microsoft.appcenter.channel.DefaultChannel.checkPendingLogs(DefaultChannel.java:726)
	at com.microsoft.appcenter.channel.DefaultChannel.addGroup(DefaultChannel.java:240)
	at com.microsoft.appcenter.AppCenter.finishConfiguration(AppCenter.java:865)
	at com.microsoft.appcenter.AppCenter.access$500(AppCenter.java:61)
	at com.microsoft.appcenter.AppCenter$5.run(AppCenter.java:737)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loop(Unknown Source:250)
	at android.os.HandlerThread.run(Unknown Source:28)
</code></pre></details>

**Comment by Lehmaning** [comment]
更新完 Tg 频道的最新版本后没有闪退了，感谢。

**Comment by ReAtopos** [comment]
> 

请问你下载的版本有夜间模式吗
