### ISSUE TITLE
[QQ8.8.68] 无法进入qnotified设置

### ISSUE THREAD

**Issue by RimuruChan** [ferredoxin/QNotified#1255]
**QQ(TIM)版本/QQ(TIM) Version**

* 8.8.68

**模块版本/Module Version**

* 1.0.0

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* lsposed-riru 1.6.5

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)

正常进入菜单或通过qn进入菜单

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

[ 2022-01-27T21:53:14.408    10232: 21974: 21974 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tencent.mobileqq/me.singleneuron.qn_kernel.ui.activity.SettingActivity}: android.content.res.Resources$NotFoundException: Drawable com.tencent.mobileqq.zplan_impl:id/tyl with resource ID #0x7506004d
	at android.app.ActivityThread.performLaunchActivity(Unknown Source:697)
	at android.app.ActivityThread.handleLaunchActivity(Unknown Source:94)
	at android.app.servertransaction.LaunchActivityItem.execute(Unknown Source:12)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(Unknown Source:77)
	at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:73)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:127)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loopOnce(Unknown Source:176)
	at android.os.Looper.loop(Unknown Source:77)
	at android.app.ActivityThread.main(Unknown Source:138)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:306)
Caused by: android.content.res.Resources$NotFoundException: Drawable com.tencent.mobileqq.zplan_impl:id/tyl with resource ID #0x7506004d
Caused by: android.content.res.Resources$NotFoundException: Resource "com.tencent.mobileqq.zplan_impl:id/tyl" (7506004d) is not a Drawable (color or path): TypedValue{t=0x12/d=0x0 a=16 r=0x7506004d}
	at android.content.res.ResourcesImpl.loadDrawableForCookie(Unknown Source:203)
	at android.content.res.ResourcesImpl.loadDrawable(Unknown Source:157)
	at android.content.res.MiuiResourcesImpl.loadDrawable(Unknown Source:24)
	at android.content.res.Resources.loadDrawable(Unknown Source:7)
	at android.content.res.Resources.getDrawableForDensity(Unknown Source:10)
	at android.content.res.Resources.getDrawable(Unknown Source:1)
	at android.content.Context.getDrawable(Unknown Source:8)
	at androidx.core.content.ContextCompat$Api21Impl.getDrawable(ContextCompat.java:864)
	at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:483)
	at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:148)
	at androidx.appcompat.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:480)
	at androidx.appcompat.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:93)
	at androidx.appcompat.app.AppCompatDelegateImpl.attachToWindow(AppCompatDelegateImpl.java:803)
	at androidx.appcompat.app.AppCompatDelegateImpl.ensureWindow(AppCompatDelegateImpl.java:779)
	at androidx.appcompat.app.AppCompatDelegateImpl.onCreate(AppCompatDelegateImpl.java:506)
	at androidx.appcompat.app.AppCompatActivity$2.onContextAvailable(AppCompatActivity.java:131)
	at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:320)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
	at org.ferredoxin.ferredoxinui.qnotified_style.activity.MaiTungTMStyleActivity.onCreate(MaiTungTMStyleActivity.kt:45)
	at me.singleneuron.qn_kernel.ui.activity.SettingActivity.onCreate(SettingActivity.kt:52)
	at android.app.Activity.performCreate(Unknown Source:125)
	at android.app.Activity.performCreate(Unknown Source:1)
	at android.app.Instrumentation.callActivityOnCreate(Unknown Source:3)
	at android.app.ActivityThread.performLaunchActivity(Unknown Source:433)
	at android.app.ActivityThread.handleLaunchActivity(Unknown Source:94)
	at android.app.servertransaction.LaunchActivityItem.execute(Unknown Source:12)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(Unknown Source:77)
	at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:73)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:127)
	at android.os.Handler.dispatchMessage(Unknown Source:19)

</code></pre></details>

**Comment by qwq233** [comment]
#1253 Duplicate
