### ISSUE TITLE
[此处填写QQ或TIM版本号] 简要概况问题

### ISSUE THREAD

**Issue by longlongago7** [ferredoxin/QNotified#1312]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ的关于里面显示的是8.8.93.8120/Qnotified显示的是8.8.93 (2886)

**模块版本/Module Version**

* Qnotified 1.0.1.6f5520f

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* 太极阴 承影9.0.1.04182224-7874

**问题的具体描述/Detailed Description of the Bug**

* QQ净化—拓展—以图片方式打开闪照 在开启这个功能时显示 初始化失败
*手机型号小米12Pro（骁龙8gen1）最近把QQ换成了系统商店提供的“64位版本”之后就变成这个样了
  求帮助

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

（此处贴日志）

</code></pre></details>

**Comment by cinit** [comment]
@longlongago7 你用 qa 吧

**Comment by longlongago7** [comment]
> @longlongago7 你用 qa 吧

也是提示的初始化失败

**Comment by longlongago7** [comment]
> @longlongago7 你用 qa 吧

也是提示的初始化失败
<details><summary>展开查看</summary><pre><code>

1.2.5.r551.1acbd2e
QQ8.8.93(2886)
cc.ioctl.hook.FlashPicHook
isInitialized: true
isInitializationSuccessful: false
isEnabled: true
isAvailable: true
isPreparationRequired: false
errors: 1
java.lang.NullPointerException: method == null
	at java.util.Objects.requireNonNull(Objects.java:245)
	at cc.ioctl.util.HookUtils.hookBeforeIfEnabled(HookUtils.java:160)
	at cc.ioctl.hook.FlashPicHook.initOnce(FlashPicHook.java:102)
	at io.github.qauxv.hook.BaseFunctionHook.initialize(BaseFunctionHook.kt:60)
	at io.github.qauxv.core.InjectDelayableHooks.step(InjectDelayableHooks.java:158)
	at io.github.qauxv.core.MainHook$1.afterHookedMethod(MainHook.java:135)
	at de.robv.android.xposed.ExposedHelper.afterHookedMethod(SourceFile:52)
	at exp.apz$ʼ.ᐝ(SourceFile:334)
	at exp.anj.a(SourceFile:262)
	at exp.anj.a(SourceFile:191)
	at com.tencent.mobileqq.startup.step.LoadData_532597895264.doStep(Unknown Source:11)
	at com.tencent.mobileqq.startup.step.Step.step(P:10)
	at com.tencent.mobileqq.startup.step.Step.doStep(P:3)
	at com.tencent.mobileqq.startup.step.Step.step(P:10)
	at com.tencent.mobileqq.startup.step.Step.run(P:1)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.os.HandlerThread.run(HandlerThread.java:67)



</code></pre></details>

**Comment by Cryolitia** [comment]
@longlongago7 xswl

**Comment by longlongago7** [comment]
> @longlongago7 xswl

sdl，wsl

**Comment by Arizzer** [comment]
我也是，不知道为什么......

**Comment by Ashelia1015** [comment]
我也是..  重新设置就显示初始化失败.  退回QQ8.8.50后 恢复正常.. 但是屏蔽更新提示的功能也没用了
