### ISSUE TITLE
[BUG] qq8.5.0屏蔽@全体成员、群红包失效

### ISSUE THREAD

**Issue by Thiasap** [ferredoxin/QNotified#430]
**QQ(TIM)版本/QQ(TIM) Version**
QQ 8.5.0.5025 

**模块版本/Module Version**
Commits on Jan 10, 2021，这个Commit编译的版本，截至目前的最新版

**使用的框架名称与框架版本/Xposed Framework and Framework Version**
Edxp

**问题的具体描述/Detailed Description of the Bug**

屏蔽@全体成员界面无法加载群号导致功能失效，疑似新版QQ更改了类名导致找不到，不知道是否是因为我的版本太旧导致。最近忙项目，希望有大佬能看看
logcat如下：
`2021-01-14 16:09:45.144 19921-19921/? E/EdXposed-Bridge: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])' on a null object reference
        at nil.nadph.qnotified.activity.TroopSelectActivity.getTroopInfoListRaw(TroopSelectActivity.java:5)
        at nil.nadph.qnotified.activity.TroopSelectActivity.getTroopInfoList(TroopSelectActivity.java:2)
        at nil.nadph.qnotified.activity.TroopSelectActivity.doOnCreate(TroopSelectActivity.java:59)
        at mqq.app.AppActivity.onCreate(P:90)
        at android.app.Activity.performCreate(Activity.java:8143)
        at android.app.Activity.performCreate(Activity.java:8115)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
        at nil.nadph.qnotified.MainHook$MyInstrumentation.callActivityOnCreate(MainHook.java:6)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3513)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3700)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2136)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8061)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
`

**Comment by Thiasap** [comment]
唉QQ好友选择列表(小尾巴里)也是这样，脑壳疼。

`2021-01-14 16:36:41.480 2554-2554/? E/QNdump: java.lang.IllegalArgumentException: boolean is not visible from class loader
        at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:626)
        at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:602)
        at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230)
        at java.lang.reflect.WeakCache.get(WeakCache.java:127)
        at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:438)
        at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:873)
        at nil.nadph.qnotified.util.FaceImpl.createListener(FaceImpl.java:11)
        at nil.nadph.qnotified.util.FaceImpl.<init>(FaceImpl.java:13)
        at nil.nadph.qnotified.util.FaceImpl.getInstance(FaceImpl.java:2)
        at nil.nadph.qnotified.activity.FriendSelectActivity.doOnCreate(FriendSelectActivity.java:4)
        at mqq.app.AppActivity.onCreate(P:90)
        at android.app.Activity.performCreate(Activity.java:8143)
        at android.app.Activity.performCreate(Activity.java:8115)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
        at nil.nadph.qnotified.MainHook$MyInstrumentation.callActivityOnCreate(MainHook.java:6)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3513)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3700)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2136)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8061)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967) 
 ` 
 
`2021-01-14 16:36:41.480 2554-2554/? E/EdXposed-Bridge: java.lang.IllegalArgumentException: boolean is not visible from class loader
        at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:626)
        at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:602)
        at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230)
        at java.lang.reflect.WeakCache.get(WeakCache.java:127)
        at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:438)
        at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:873)
        at nil.nadph.qnotified.util.FaceImpl.createListener(FaceImpl.java:11)
        at nil.nadph.qnotified.util.FaceImpl.<init>(FaceImpl.java:13)
        at nil.nadph.qnotified.util.FaceImpl.getInstance(FaceImpl.java:2)
        at nil.nadph.qnotified.activity.FriendSelectActivity.doOnCreate(FriendSelectActivity.java:4)
        at mqq.app.AppActivity.onCreate(P:90)
        at android.app.Activity.performCreate(Activity.java:8143)
        at android.app.Activity.performCreate(Activity.java:8115)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
        at nil.nadph.qnotified.MainHook$MyInstrumentation.callActivityOnCreate(MainHook.java:6)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3513)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3700)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2136)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8061)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967) 
` 
 
`2021-01-14 16:36:41.543 2554-2554/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tencent.mobileqq, PID: 2554
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.Bitmap nil.nadph.qnotified.util.FaceImpl.getBitmapFromCache(int, java.lang.String)' on a null object reference
        at nil.nadph.qnotified.activity.FriendSelectActivity.getView(FriendSelectActivity.java:15)
        at nil.nadph.qnotified.activity.FriendSelectActivity$1.getView(FriendSelectActivity.java:1)
        at com.tencent.widget.AbsListView.obtainView(P:2297)
        at com.tencent.widget.ListView.makeAndAddView(P:2068)
        at com.tencent.widget.ListView.fillDown(P:875)
        at com.tencent.widget.ListView.fillFromTop(P:936)
        at com.tencent.widget.ListView.layoutChildren(P:1868)
        at com.tencent.widget.AbsListView.onLayout(P:2121)
        at com.tencent.widget.ListView.onLayout(P:1681)
        at android.view.View.layout(View.java:23067)
        at android.view.ViewGroup.layout(ViewGroup.java:6460)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:23067)
        at android.view.ViewGroup.layout(ViewGroup.java:6460)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:23067)
        at android.view.ViewGroup.layout(ViewGroup.java:6460)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
        at android.view.View.layout(View.java:23067)
        at android.view.ViewGroup.layout(ViewGroup.java:6460)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:23067)
        at android.view.ViewGroup.layout(ViewGroup.java:6460)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:23067)
        at android.view.ViewGroup.layout(ViewGroup.java:6460)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
        at com.tencent.mobileqq.activity.fling.TopGestureLayout.onLayout(P:358)
        at android.view.View.layout(View.java:23067)
        at android.view.ViewGroup.layout(ViewGroup.java:6460)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:797)
        at android.view.View.layout(View.java:23067)
        at android.view.ViewGroup.layout(ViewGroup.java:6460)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3612)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3072)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2065)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8497)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1076)
        at android.view.Choreographer.doCallbacks(Choreographer.java:897)
        at android.view.Choreographer.doFrame(Choreographer.java:826)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1061)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8061)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
`
