### ISSUE TITLE
[8.7.5] nightly版在android 7上面显示激活，但qq里面找不到qnotified设置

### ISSUE THREAD

**Issue by youling257** [ferredoxin/QNotified#884]
05-13 17:49:59.783  9323  9323 E art     : No implementation found for int nil.nadph.qnotified.util.Natives.getpagesize() (tried Java_nil_nadph_qnotified_util_Natives_getpagesize and Java_nil_nadph_qnotified_util_Natives_getpagesize__)
05-13 17:49:59.786  9323  9323 D houdini : [9323] Added shared library /data/user/0/com.tencent.mobileqq/files/qn_dyn_lib/libnatives.so.1620877991.armeabi-v7a for ClassLoader by Native Bridge.
05-13 17:49:59.787  9323  9323 E art     : Failed to register native method com.tencent.mmkv.MMKV.isFileValid(Ljava/lang/String;Ljava/lang/String;)Z in /data/app/com.tencent.mobileqq-2/base.apk:classes4.dex
05-13 17:49:59.787  9323  9323 E art     : ----- class 'Lcom/tencent/mmkv/MMKV;' cl=0x12c51e50 -----
05-13 17:49:59.788  9323  9323 E art     :   objectSize=417 (180 from super)
05-13 17:49:59.788  9323  9323 E art     :   access=0x0000.0001
05-13 17:49:59.788  9323  9323 E art     :   super='java.lang.Class<java.lang.Object>' (cl=0x0)
05-13 17:49:59.788  9323  9323 E art     :   interfaces (2):
05-13 17:49:59.788  9323  9323 E art     :      0: java.lang.Class<android.content.SharedPreferences> (cl=0x0)
05-13 17:49:59.788  9323  9323 E art     :      1: java.lang.Class<android.content.SharedPreferences$Editor> (cl=0x0)
05-13 17:49:59.788  9323  9323 E art     :   vtable (51 entries, 11 in super):
05-13 17:49:59.788  9323  9323 E art     :      0: int com.tencent.mmkv.MMKV.a(java.lang.String, int)
05-13 17:49:59.789  9323  9323 E art     :      1: long com.tencent.mmkv.MMKV.a(java.lang.String, long)
05-13 17:49:59.789  9323  9323 E art     :      2: java.lang.String com.tencent.mmkv.MMKV.a(java.lang.String)
05-13 17:49:59.789  9323  9323 E art     :      3: java.lang.String com.tencent.mmkv.MMKV.a(java.lang.String, java.lang.String)
05-13 17:49:59.789  9323  9323 E art     :      4: java.util.Set com.tencent.mmkv.MMKV.a(java.lang.String, java.util.Set)
05-13 17:49:59.789  9323  9323 E art     :      5: java.util.Set com.tencent.mmkv.MMKV.a(java.lang.String, java.util.Set, java.lang.Class)
05-13 17:49:59.789  9323  9323 E art     :      6: void com.tencent.mmkv.MMKV.a(java.lang.String)
05-13 17:49:59.789  9323  9323 E art     :      7: boolean com.tencent.mmkv.MMKV.a(java.lang.String)
05-13 17:49:59.789  9323  9323 E art     :      8: boolean com.tencent.mmkv.MMKV.a(java.lang.String, int)
05-13 17:49:59.790  9323  9323 E art     :      9: boolean com.tencent.mmkv.MMKV.a(java.lang.String, long)
05-13 17:49:59.790  9323  9323 E art     :     10: boolean com.tencent.mmkv.MMKV.a(java.lang.String, java.lang.String)
05-13 17:49:59.790  9323  9323 E art     :     11: boolean com.tencent.mmkv.MMKV.a(java.lang.String, java.util.Set)
05-13 17:49:59.790  9323  9323 E art     :     12: boolean com.tencent.mmkv.MMKV.a(java.lang.String, boolean)
05-13 17:49:59.790  9323  9323 E art     :     13: java.lang.String[] com.tencent.mmkv.MMKV.allKeys()
05-13 17:49:59.790  9323  9323 E art     :     14: void com.tencent.mmkv.MMKV.apply()
05-13 17:49:59.790  9323  9323 E art     :     15: int com.tencent.mmkv.MMKV.ashmemFD()
05-13 17:49:59.790  9323  9323 E art     :     16: int com.tencent.mmkv.MMKV.ashmemMetaFD()
05-13 17:49:59.791  9323  9323 E art     :     17: boolean com.tencent.mmkv.MMKV.b(java.lang.String, boolean)
05-13 17:49:59.791  9323  9323 E art     :     18: void com.tencent.mmkv.MMKV.checkContentChangedByOuterProcess()
05-13 17:49:59.791  9323  9323 E art     :     19: void com.tencent.mmkv.MMKV.checkReSetCryptKey(java.lang.String)
05-13 17:49:59.791  9323  9323 E art     :     20: android.content.SharedPreferences$Editor com.tencent.mmkv.MMKV.clear()
05-13 17:49:59.791  9323  9323 E art     :     21: void com.tencent.mmkv.MMKV.clearAll()
05-13 17:49:59.791  9323  9323 E art     :     22: void com.tencent.mmkv.MMKV.clearMemoryCache()
05-13 17:49:59.791  9323  9323 E art     :     23: void com.tencent.mmkv.MMKV.close()
05-13 17:49:59.791  9323  9323 E art     :     24: boolean com.tencent.mmkv.MMKV.commit()
05-13 17:49:59.792  9323  9323 E art     :     25: boolean com.tencent.mmkv.MMKV.contains(java.lang.String)
05-13 17:49:59.792  9323  9323 E art     :     26: java.lang.String com.tencent.mmkv.MMKV.cryptKey()
05-13 17:49:59.792  9323  9323 E art     :     27: android.content.SharedPreferences$Editor com.tencent.mmkv.MMKV.edit()
05-13 17:49:59.792  9323  9323 E art     :     28: java.util.Map com.tencent.mmkv.MMKV.getAll()
05-13 17:49:59.792  9323  9323 E art     :     29: boolean com.tencent.mmkv.MMKV.getBoolean(java.lang.String, boolean)
05-13 17:49:59.792  9323  9323 E art     :     30: float com.tencent.mmkv.MMKV.getFloat(java.lang.String, float)
05-13 17:49:59.792  9323  9323 E art     :     31: int com.tencent.mmkv.MMKV.getInt(java.lang.String, int)
05-13 17:49:59.793  9323  9323 E art     :     32: long com.tencent.mmkv.MMKV.getLong(java.lang.String, long)
05-13 17:49:59.793  9323  9323 E art     :     33: java.lang.String com.tencent.mmkv.MMKV.getString(java.lang.String, java.lang.String)
05-13 17:49:59.793  9323  9323 E art     :     34: java.util.Set com.tencent.mmkv.MMKV.getStringSet(java.lang.String, java.util.Set)
05-13 17:49:59.793  9323  9323 E art     :     35: void com.tencent.mmkv.MMKV.lock()
05-13 17:49:59.793  9323  9323 E art     :     36: java.lang.String com.tencent.mmkv.MMKV.mmapID()
05-13 17:49:59.793  9323  9323 E art     :     37: android.content.SharedPreferences$Editor com.tencent.mmkv.MMKV.putBoolean(java.lang.String, boolean)
05-13 17:49:59.793  9323  9323 E art     :     38: android.content.SharedPreferences$Editor com.tencent.mmkv.MMKV.putFloat(java.lang.String, float)
05-13 17:49:59.793  9323  9323 E art     :     39: android.content.SharedPreferences$Editor com.tencent.mmkv.MMKV.putInt(java.lang.String, int)
05-13 17:49:59.794  9323  9323 E art     :     40: android.content.SharedPreferences$Editor com.tencent.mmkv.MMKV.putLong(java.lang.String, long)
05-13 17:49:59.794  9323  9323 E art     :     41: android.content.SharedPreferences$Editor com.tencent.mmkv.MMKV.putString(java.lang.String, java.lang.String)
05-13 17:49:59.794  9323  9323 E art     :     42: android.content.SharedPreferences$Editor com.tencent.mmkv.MMKV.putStringSet(java.lang.String, java.util.Set)
05-13 17:49:59.794  9323  9323 E art     :     43: boolean com.tencent.mmkv.MMKV.reKey(java.lang.String)
05-13 17:49:59.794  9323  9323 E art     :     44: void com.tencent.mmkv.MMKV.registerOnSharedPreferenceChangeListener(android.content.SharedPreferences$OnSharedPreferenceChangeListener)
05-13 17:49:59.794  9323  9323 E art     :     45: android.content.SharedPreferences$Editor com.tencent.mmkv.MMKV.remove(java.lang.String)
05-13 17:49:59.794  9323  9323 E art     :     46: void com.tencent.mmkv.MMKV.removeValuesForKeys(java.lang.String[])
05-13 17:49:59.795  9323  9323 E art     :     47: void com.tencent.mmkv.MMKV.trim()
05-13 17:49:59.795  9323  9323 E art     :     48: boolean com.tencent.mmkv.MMKV.tryLock()
05-13 17:49:59.795  9323  9323 E art     :     49: void com.tencent.mmkv.MMKV.unlock()
05-13 17:49:59.795  9323  9323 E art     :     50: void com.tencent.mmkv.MMKV.unregisterOnSharedPreferenceChangeListener(android.content.SharedPreferences$OnSharedPreferenceChangeListener)
05-13 17:49:59.795  9323  9323 E art     :   direct methods (53 entries):
05-13 17:49:59.795  9323  9323 E art     :      0: void com.tencent.mmkv.MMKV.<clinit>()
05-13 17:49:59.795  9323  9323 E art     :      1: void com.tencent.mmkv.MMKV.<init>(long)
05-13 17:49:59.795  9323  9323 E art     :      2: int com.tencent.mmkv.MMKV.a(com.tencent.mmkv.MMKVLogLevel)
05-13 17:49:59.796  9323  9323 E art     :      3: com.tencent.mmkv.MMKV com.tencent.mmkv.MMKV.a(long, java.lang.String, int)
05-13 17:49:59.796  9323  9323 E art     :      4: com.tencent.mmkv.MMKV com.tencent.mmkv.MMKV.a(android.content.Context, java.lang.String, int, int, java.lang.String)
05-13 17:49:59.796  9323  9323 E art     :      5: com.tencent.mmkv.MMKV com.tencent.mmkv.MMKV.a(java.lang.String, int)
05-13 17:49:59.796  9323  9323 E art     :      6: com.tencent.mmkv.MMKV com.tencent.mmkv.MMKV.a(java.lang.String, int, int, java.lang.String)
05-13 17:49:59.796  9323  9323 E art     :      7: com.tencent.mmkv.MMKV com.tencent.mmkv.MMKV.a(java.lang.String, int, java.lang.String)
05-13 17:49:59.796  9323  9323 E art     :      8: java.lang.String com.tencent.mmkv.MMKV.a(java.lang.String, com.tencent.mmkv.MMKV$LibLoader)
05-13 17:49:59.796  9323  9323 E art     :      9: java.lang.String com.tencent.mmkv.MMKV.a(java.lang.String, com.tencent.mmkv.MMKV$LibLoader, com.tencent.mmkv.MMKVLogLevel)
05-13 17:49:59.797  9323  9323 E art     :     10: void com.tencent.mmkv.MMKV.a(com.tencent.mmkv.MMKVLogLevel, java.lang.String)
05-13 17:49:59.797  9323  9323 E art     :     11: boolean com.tencent.mmkv.MMKV.checkProcessMode(long)
05-13 17:49:59.797  9323  9323 E art     :     12: boolean com.tencent.mmkv.MMKV.containsKey(long, java.lang.String)
05-13 17:49:59.797  9323  9323 E art     :     13: long com.tencent.mmkv.MMKV.count(long)
05-13 17:49:59.797  9323  9323 E art     :     14: long com.tencent.mmkv.MMKV.createNB(int)
05-13 17:49:59.797  9323  9323 E art     :     15: boolean com.tencent.mmkv.MMKV.decodeBool(long, java.lang.String, boolean)
05-13 17:49:59.797  9323  9323 E art     :     16: byte[] com.tencent.mmkv.MMKV.decodeBytes(long, java.lang.String)
05-13 17:49:59.798  9323  9323 E art     :     17: double com.tencent.mmkv.MMKV.decodeDouble(long, java.lang.String, double)
05-13 17:49:59.798  9323  9323 E art     :     18: float com.tencent.mmkv.MMKV.decodeFloat(long, java.lang.String, float)
05-13 17:49:59.798  9323  9323 E art     :     19: int com.tencent.mmkv.MMKV.decodeInt(long, java.lang.String, int)
05-13 17:49:59.798  9323  9323 E art     :     20: long com.tencent.mmkv.MMKV.decodeLong(long, java.lang.String, long)
05-13 17:49:59.798  9323  9323 E art     :     21: java.lang.String com.tencent.mmkv.MMKV.decodeString(long, java.lang.String, java.lang.String)
05-13 17:49:59.798  9323  9323 E art     :     22: java.lang.String[] com.tencent.mmkv.MMKV.decodeStringSet(long, java.lang.String)
05-13 17:49:59.798  9323  9323 E art     :     23: void com.tencent.mmkv.MMKV.destroyNB(long, int)
05-13 17:49:59.799  9323  9323 E art     :     24: boolean com.tencent.mmkv.MMKV.encodeBool(long, java.lang.String, boolean)
05-13 17:49:59.799  9323  9323 E art     :     25: boolean com.tencent.mmkv.MMKV.encodeBytes(long, java.lang.String, byte[])
05-13 17:49:59.799  9323  9323 E art     :     26: boolean com.tencent.mmkv.MMKV.encodeDouble(long, java.lang.String, double)
05-13 17:49:59.799  9323  9323 E art     :     27: boolean com.tencent.mmkv.MMKV.encodeFloat(long, java.lang.String, float)
05-13 17:49:59.799  9323  9323 E art     :     28: boolean com.tencent.mmkv.MMKV.encodeInt(long, java.lang.String, int)
05-13 17:49:59.799  9323  9323 E art     :     29: boolean com.tencent.mmkv.MMKV.encodeLong(long, java.lang.String, long)
05-13 17:49:59.799  9323  9323 E art     :     30: boolean com.tencent.mmkv.MMKV.encodeSet(long, java.lang.String, java.lang.String[])
05-13 17:49:59.799  9323  9323 E art     :     31: boolean com.tencent.mmkv.MMKV.encodeString(long, java.lang.String, java.lang.String)
05-13 17:49:59.800  9323  9323 E art     :     32: long com.tencent.mmkv.MMKV.getDefaultMMKV(int, java.lang.String)
05-13 17:49:59.800  9323  9323 E art     :     33: long com.tencent.mmkv.MMKV.getMMKVWithAshmemFD(java.lang.String, int, int, java.lang.String)
05-13 17:49:59.800  9323  9323 E art     :     34: long com.tencent.mmkv.MMKV.getMMKVWithID(java.lang.String, int, java.lang.String, java.lang.String)
05-13 17:49:59.800  9323  9323 E art     :     35: long com.tencent.mmkv.MMKV.getMMKVWithIDAndSize(java.lang.String, int, int, java.lang.String)
05-13 17:49:59.800  9323  9323 E art     :     36: boolean com.tencent.mmkv.MMKV.isFileValid(java.lang.String)
05-13 17:49:59.800  9323  9323 E art     :     37: void com.tencent.mmkv.MMKV.jniInitialize(java.lang.String, int)
05-13 17:49:59.800  9323  9371 D QQCrashReportManager: CrashReport init finished.
05-13 17:49:59.800  9323  9323 E art     :     38: void com.tencent.mmkv.MMKV.mmkvLogImp(int, java.lang.String, int, java.lang.String, java.lang.String)
05-13 17:49:59.801  9323  9323 E art     :     39: void com.tencent.mmkv.MMKV.onContentChangedByOuterProcess(java.lang.String)
05-13 17:49:59.801  9323  9323 E art     :     40: void com.tencent.mmkv.MMKV.onExit()
05-13 17:49:59.801  9323  9323 E art     :     41: int com.tencent.mmkv.MMKV.onMMKVCRCCheckFail(java.lang.String)
05-13 17:49:59.801  9323  9323 E art     :     42: int com.tencent.mmkv.MMKV.onMMKVFileLengthError(java.lang.String)
05-13 17:49:59.801  9323  9323 E art     :     43: int com.tencent.mmkv.MMKV.pageSize()
05-13 17:49:59.801  9323  9323 E art     :     44: void com.tencent.mmkv.MMKV.removeValueForKey(long, java.lang.String)
05-13 17:49:59.802  9323  9323 E art     :     45: void com.tencent.mmkv.MMKV.setCallbackHandler(boolean, boolean)
05-13 17:49:59.802  9323  9323 E art     :     46: void com.tencent.mmkv.MMKV.setLogLevel(int)
05-13 17:49:59.802  9323  9323 E art     :     47: void com.tencent.mmkv.MMKV.setWantsContentChangeNotify(boolean)
05-13 17:49:59.802  9323  9323 E art     :     48: void com.tencent.mmkv.MMKV.sync(boolean)
05-13 17:49:59.802  9323  9323 E art     :     49: long com.tencent.mmkv.MMKV.totalSize(long)
05-13 17:49:59.802  9323  9323 E art     :     50: int com.tencent.mmkv.MMKV.valueSize(long, java.lang.String, boolean)
05-13 17:49:59.802  9323  9323 E art     :     51: java.lang.String com.tencent.mmkv.MMKV.version()
05-13 17:49:59.802  9323  9371 I beacon  : beacon logAble: false
05-13 17:49:59.802  9323  9323 E art     :     52: int com.tencent.mmkv.MMKV.writeValueToNB(long, java.lang.String, long, int)
05-13 17:49:59.803  9323  9323 E art     :   static fields (9 entries):
05-13 17:49:59.803  9323  9323 E art     :      0: com.tencent.mmkv.MMKVContentChangeNotification com.tencent.mmkv.MMKV.a
05-13 17:49:59.803  9323  9323 E art     :      1: com.tencent.mmkv.MMKVHandler com.tencent.mmkv.MMKV.a
05-13 17:49:59.803  9323  9371 D QQBeaconReport: start: isDebugVersion = false
05-13 17:49:59.803  9323  9323 E art     :      2: java.lang.String com.tencent.mmkv.MMKV.a
05-13 17:49:59.803  9323  9387 I beacon  : beacon logAble: false
05-13 17:49:59.803  9323  9371 D QQBeaconReport: setUserId = 603418528
05-13 17:49:59.803  9323  9323 E art     :      3: java.util.EnumMap com.tencent.mmkv.MMKV.a
05-13 17:49:59.804  9323  9323 E art     :      4: java.util.HashMap com.tencent.mmkv.MMKV.a
05-13 17:49:59.804  9323  9323 E art     :      5: java.util.Set com.tencent.mmkv.MMKV.a
05-13 17:49:59.804  9323  9323 E art     :      6: boolean com.tencent.mmkv.MMKV.a
05-13 17:49:59.804  9323  9323 E art     :      7: com.tencent.mmkv.MMKVLogLevel[] com.tencent.mmkv.MMKV.a
05-13 17:49:59.804  9323  9323 E art     :      8: java.util.EnumMap com.tencent.mmkv.MMKV.b
05-13 17:49:59.804  9323  9323 E art     :   instance fields (1 entries):
05-13 17:49:59.805  9323  9323 E art     :      0: long com.tencent.mmkv.MMKV.nativeHandle
05-13 17:49:59.805  9323  9323 E art     : 
05-13 17:49:59.805  9323  9323 E MMKV    : <native-bridge.cpp:69::MMKV_JNI_OnLoad> fail to register native methods for class com/tencent/mmkv/MMKV, ret = -1
05-13 17:49:59.805  9323  9371 D DtSdkInitStep: init beacon-dt success ! cost : 0 ms
05-13 17:49:59.806  9323  9323 E QNdump  : java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad in "/data/user/0/com.tencent.mobileqq/files/qn_dyn_lib/libnatives.so.1620877991.armeabi-v7a": -4
05-13 17:49:59.806  9323  9323 E QNdump  : 	at java.lang.Runtime.load0(Runtime.java:908)
05-13 17:49:59.806  9323  9323 E QNdump  : 	at java.lang.System.load(System.java:1537)
05-13 17:49:59.806  9323  9323 E QNdump  : 	at nil.nadph.qnotified.util.Natives.load(Natives.java:150)
05-13 17:49:59.806  9323  9323 E QNdump  : 	at nil.nadph.qnotified.startup.StartupRoutine.execPostStartupInit(StartupRoutine.java:56)
05-13 17:49:59.806  9323  9323 E QNdump  : 	at nil.nadph.qnotified.startup.StartupHook.execStartupInit(StartupHook.java:76)
05-13 17:49:59.806  9323  9323 E QNdump  : 	at nil.nadph.qnotified.startup.StartupHook$1.afterHookedMethod(StartupHook.java:197)
05-13 17:49:59.806  9323  9323 E QNdump  : 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:374)
05-13 17:49:59.806  9323  9323 E QNdump  : 	at com.tencent.mobileqq.startup.step.LoadDex.doStep(<Xposed>)
05-13 17:49:59.806  9323  9323 E QNdump  : 	at com.tencent.mobileqq.startup.step.Step.step(P:129)
05-13 17:49:59.806  9323  9323 E QNdump  : 	at com.tencent.mobileqq.startup.step.Step.doStep(P:161)
05-13 17:49:59.806  9323  9323 E QNdump  : 	at com.tencent.mobileqq.startup.step.Step.step(P:129)
05-13 17:49:59.806  9323  9323 E QNdump  : 	at com.tencent.mobileqq.startup.director.StartupDirector.a(P:403)
05-13 17:49:59.806  9323  9323 E QNdump  : 	at com.tencent.common.app.BaseApplicationImpl.onCreate(P:333)
05-13 17:49:59.806  9323  9323 E QNdump  : 	at com.tencent.mobileqq.qfix.QFixApplication.onCreate(P:30)
05-13 17:49:59.806  9323  9323 E QNdump  : 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
05-13 17:49:59.806  9323  9323 E QNdump  : 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5448)
05-13 17:49:59.806  9323  9323 E QNdump  : 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
05-13 17:49:59.806  9323  9323 E QNdump  : 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
05-13 17:49:59.806  9323  9323 E QNdump  : 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
05-13 17:49:59.806  9323  9323 E QNdump  : 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
05-13 17:49:59.806  9323  9323 E QNdump  : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1564)
05-13 17:49:59.806  9323  9323 E QNdump  : 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-13 17:49:59.806  9323  9323 E QNdump  : 	at android.os.Looper.loop(Looper.java:154)
05-13 17:49:59.806  9323  9323 E QNdump  : 	at android.app.ActivityThread.main(ActivityThread.java:6186)
05-13 17:49:59.806  9323  9323 E QNdump  : 	at java.lang.reflect.Method.invoke(Native Method)
05-13 17:49:59.806  9323  9323 E QNdump  : 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:890)
05-13 17:49:59.806  9323  9323 E QNdump  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:780)
05-13 17:49:59.806  9323  9323 E QNdump  : 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
05-13 17:49:59.807  9323  9323 E Xposed  : java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad in "/data/user/0/com.tencent.mobileqq/files/qn_dyn_lib/libnatives.so.1620877991.armeabi-v7a": -4
05-13 17:49:59.807  9323  9323 E Xposed  : 	at java.lang.Runtime.load0(Runtime.java:908)
05-13 17:49:59.807  9323  9323 E Xposed  : 	at java.lang.System.load(System.java:1537)
05-13 17:49:59.807  9323  9323 E Xposed  : 	at nil.nadph.qnotified.util.Natives.load(Natives.java:150)
05-13 17:49:59.807  9323  9323 E Xposed  : 	at nil.nadph.qnotified.startup.StartupRoutine.execPostStartupInit(StartupRoutine.java:56)
05-13 17:49:59.807  9323  9323 E Xposed  : 	at nil.nadph.qnotified.startup.StartupHook.execStartupInit(StartupHook.java:76)
05-13 17:49:59.807  9323  9323 E Xposed  : 	at nil.nadph.qnotified.startup.StartupHook$1.afterHookedMethod(StartupHook.java:197)
05-13 17:49:59.807  9323  9323 E Xposed  : 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:374)
05-13 17:49:59.807  9323  9323 E Xposed  : 	at com.tencent.mobileqq.startup.step.LoadDex.doStep(<Xposed>)
05-13 17:49:59.807  9323  9323 E Xposed  : 	at com.tencent.mobileqq.startup.step.Step.step(P:129)
05-13 17:49:59.807  9323  9323 E Xposed  : 	at com.tencent.mobileqq.startup.step.Step.doStep(P:161)
05-13 17:49:59.807  9323  9323 E Xposed  : 	at com.tencent.mobileqq.startup.step.Step.step(P:129)
05-13 17:49:59.807  9323  9323 E Xposed  : 	at com.tencent.mobileqq.startup.director.StartupDirector.a(P:403)
05-13 17:49:59.807  9323  9323 E Xposed  : 	at com.tencent.common.app.BaseApplicationImpl.onCreate(P:333)
05-13 17:49:59.807  9323  9323 E Xposed  : 	at com.tencent.mobileqq.qfix.QFixApplication.onCreate(P:30)
05-13 17:49:59.807  9323  9323 E Xposed  : 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
05-13 17:49:59.807  9323  9323 E Xposed  : 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5448)
05-13 17:49:59.807  9323  9323 E Xposed  : 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
05-13 17:49:59.807  9323  9323 E Xposed  : 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
05-13 17:49:59.807  9323  9323 E Xposed  : 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
05-13 17:49:59.807  9323  9323 E Xposed  : 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
05-13 17:49:59.807  9323  9323 E Xposed  : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1564)
05-13 17:49:59.807  9323  9323 E Xposed  : 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-13 17:49:59.807  9323  9323 E Xposed  : 	at android.os.Looper.loop(Looper.java:154)
05-13 17:49:59.807  9323  9323 E Xposed  : 	at android.app.ActivityThread.main(ActivityThread.java:6186)
05-13 17:49:59.807  9323  9323 E Xposed  : 	at java.lang.reflect.Method.invoke(Native Method)
05-13 17:49:59.807  9323  9323 E Xposed  : 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:890)
05-13 17:49:59.807  9323  9323 E Xposed  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:780)
05-13 17:49:59.807  9323  9323 E Xposed  : 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
05-13 17:49:59.807  9323  9323 E art     : No implementation found for long nil.nadph.qnotified.util.Utils.ntGetBuildTimestamp() (tried Java_nil_nadph_qnotified_util_Utils_ntGetBuildTimestamp and Java_nil_nadph_qnotified_util_Utils_ntGetBuildTimestamp__)
05-13 17:49:59.822  9323  9323 D MSF.D.MonitorSocket: phoneDisplays: KOT49H|KTU84P, phoneModels: COOLPAD7295, appid: , version: , currVersion: 8.7.5.5330, process: , com.tencent.mobileqq:tool

**Comment by youling257** [comment]
5月5号的QNotified-release 0.8.19.0b18c90.apk能在android 7上面使用，5月10号的QNotified-release 0.8.19.0f13308.apk就不能用了

**Comment by youling257** [comment]
肯定用了不兼容老旧android 7系统的java语法

**Comment by youling257** [comment]
https://drive.google.com/drive/folders/1bq74gc8oFTERygRjgQr57H7bBS1t04jk?usp=sharing
俩版本的log
