### ISSUE TITLE
[8.7.8] qn没有生效

### ISSUE THREAD

**Issue by litianyuhehe** [ferredoxin/QNotified#904]
- [x] 是否阅读[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)

**QQ(TIM)版本/QQ(TIM) Version**

* 8.7.8

**模块版本/Module Version**

* 0.8.19.c2edc6c

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* lsposed 1.4.3 5728

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)

qn无法生效

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>
2021-05-28 13:50:38.038 E/com.tencent.mobileqq(19190-19190): java.lang.OutOfMemoryError: Failed to allocate a 2003137040 byte allocation with 767445 free bytes and 253MB until OOM, target footprint 3069781, growth limit 268435456
	at nil.nadph.qnotified.config.Table.readIRaw(Table.java:111)
	at nil.nadph.qnotified.config.Table.readIStr(Table.java:117)
	at nil.nadph.qnotified.config.ConfigManager.reload(ConfigManager.java:302)
	at nil.nadph.qnotified.config.ConfigManager.reinit(ConfigManager.java:126)
	at nil.nadph.qnotified.config.ConfigManager.<init>(ConfigManager.java:80)
	at nil.nadph.qnotified.config.ConfigManager.getDefaultConfig(ConfigManager.java:88)
	at nil.nadph.qnotified.hook.CommonDelayableHook.isEnabled(CommonDelayableHook.java:87)
	at nil.nadph.qnotified.hook.AbsDelayableHook.allowEarlyInit(AbsDelayableHook.java:49)
	at nil.nadph.qnotified.MainHook.performHook(MainHook.java:239)
	at nil.nadph.qnotified.startup.StartupRoutine.execPostStartupInit(StartupRoutine.java:63)
	at nil.nadph.qnotified.startup.StartupHook.execStartupInit(StartupHook.java:76)
	at nil.nadph.qnotified.startup.StartupHook$1.afterHookedMethod(StartupHook.java:197)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.doStep(Unknown Source:8)
	at com.tencent.mobileqq.startup.step.Step.step(P:129)
	at com.tencent.mobileqq.startup.step.Step.doStep(P:161)
	at com.tencent.mobileqq.startup.step.Step.step(P:129)
	at com.tencent.mobileqq.startup.director.StartupDirector.a(P:403)
	at com.tencent.common.app.BaseApplicationImpl.onCreate(P:333)
	at com.tencent.mobileqq.qfix.QFixApplication.onCreate(P:30)
	at mqq.app.AppContentProvider.onCreate(P:30)
	at com.tencent.biz.pubaccount.readinjoy.ReadInJoyDataProvider.onCreate(P:92)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2117)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2091)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7216)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6699)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6594)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:107)
	at LspHooker_.handleBindApplication(Unknown Source:11)
	at android.app.ActivityThread.access$1400(ActivityThread.java:229)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1892)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:228)
	at android.app.ActivityThread.main(ActivityThread.java:7589)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)
</code></pre></details>

**Comment by ketal178** [comment]
这是破烂储存库炸了，进故障排查
