### ISSUE TITLE
[QQ8.8.12] 回赞一键20赞失效

### ISSUE THREAD

**Issue by BoBppy** [ferredoxin/QNotified#999]
**QQ(TIM)版本/QQ(TIM) Version**

* QQ8.8.12

**模块版本/Module Version**

* 0.8.20.3eaaf3d

**使用的框架名称与框架版本/Xposed Framework and Framework Version**

* Lsposed1.4.7

**问题的具体描述/Detailed Description of the Bug**

*  具体描述(如复现BUG所需要的前提和必要操作等)

回赞界面无法一键20赞

**此处贴你获取到的日志信息/Log here**

<details><summary>展开查看</summary><pre><code>

08-09 10:32:33.371 E/QNdump  (21735): java.lang.NullPointerException: null cannot be cast to non-null type android.view.ViewGroup
08-09 10:32:33.371 E/QNdump  (21735): 	at me.kyuubiran.hook.SimplifyQQSettingMe$init$1.afterHookedMethod(SimplifyQQSettingMe.kt:114)
08-09 10:32:33.371 E/QNdump  (21735): 	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
08-09 10:32:33.371 E/QNdump  (21735): 	at LspHooker_.constructor(Unknown Source:17)
08-09 10:32:33.371 E/QNdump  (21735): 	at com.tencent.mobileqq.activity.home.Conversation.x(P:3837)
08-09 10:32:33.371 E/QNdump  (21735): 	at com.tencent.mobileqq.activity.home.Conversation.ak(P:3945)
08-09 10:32:33.371 E/QNdump  (21735): 	at com.tencent.mobileqq.activity.home.Conversation.f(P:467)
08-09 10:32:33.371 E/QNdump  (21735): 	at com.tencent.mobileqq.activity.home.Conversation$UICallBack.c(P:1047)
08-09 10:32:33.371 E/QNdump  (21735): 	at com.tencent.mobileqq.activity.home.Conversation$UICallBack.handleMessage(P:890)
08-09 10:32:33.371 E/QNdump  (21735): 	at com.tencent.mobileqq.utils.CustomHandler.handleMessage(P:25)
08-09 10:32:33.371 E/QNdump  (21735): 	at mqq.os.MqqHandler.dispatchMessage(P:99)
08-09 10:32:33.371 E/QNdump  (21735): 	at mqq.os.MqqMessageQueue.dequeue(P:294)
08-09 10:32:33.371 E/QNdump  (21735): 	at mqq.os.MqqMessageQueue.queueIdle(P:251)
08-09 10:32:33.371 E/QNdump  (21735): 	at android.os.MessageQueue.next(MessageQueue.java:404)
08-09 10:32:33.371 E/QNdump  (21735): 	at android.os.Looper.loop(Looper.java:183)
08-09 10:32:33.371 E/QNdump  (21735): 	at android.app.ActivityThread.main(ActivityThread.java:7664)
08-09 10:32:33.371 E/QNdump  (21735): 	at java.lang.reflect.Method.invoke(Native Method)
08-09 10:32:33.371 E/QNdump  (21735): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
08-09 10:32:33.371 E/QNdump  (21735): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

</code></pre></details>

不知道怎么精确地抓这里的bug额

**Comment by BoBppy** [comment]
（还有关闭小程序广告也不太行，但是又说禁止反馈我emmm就不开issue了。
现在这广告直接anti-AD屏蔽掉也不行了，x号有读条，必须放满15s，屏蔽的话掉条不走。
Qnotified里的关闭广告也失效（豆地主都不愉快了

**Comment by BoBppy** [comment]
#999被无情关闭（
